# Generated by Django 5.1.6 on 2025-02-21 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_project_delete_clientsmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
